PETSC_DIR=/lus/theta-fs0/projects/ATPESC2020/MathPackagesTraining2020/spack.a/opt/spack/linux-rhel7-haswell/gcc-8.2.0/petsc-3.13.3-zkhwzwtyqgrp5um7p27izmueoqm3rxfs

CFLAGS		 =
FFLAGS		 =
CPPFLAGS         =
FPPFLAGS         =
EXAMPLESC        = multidim_rosenbrock.c
EXAMPLESF        = 
EXAMPLESCH       =
EXAMPLESFH       = 
LOCDIR		 = 
MANSEC		 =
DOCS		 =
DIRS		 =
CLEANFILES   = multidim_rosenbrock

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
