CFLAGS		 =
FFLAGS		 =
CPPFLAGS         =
FPPFLAGS         =
EXAMPLESC        = multidim_rosenbrock.c shepp_logan.c
EXAMPLESF        = 
EXAMPLESCH       =
EXAMPLESFH       = 
LOCDIR		 = 
MANSEC		 =
DOCS		 =
DIRS		 =
CLEANFILES   = multidim_rosenbrock shepp_logan

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
